services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    expose:
      - "6379"

  tgba:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: "1"
      TELEGRAM_STAT: "1"
    expose:
      - "8081"
    volumes:
      - ../telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
      - ../tictacLogs:/logs

  bot:
    build: .
    container_name: aiogram_bot
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - BOT_API_SERVER=${BOT_API_SERVER}
      - BOT_PROXY_URL=${BOT_PROXY_URL}
      - WEBHOOK_BASE_URL=http://bot:8080
      - WEBHOOK_PATH=/webhook
      - WEBHOOK_LISTEN_HOST=0.0.0.0
      - WEBHOOK_LISTEN_PORT=8080
    volumes:
      - .:/app
    expose:
      - "8080"
    depends_on:
      - db
      - redis
      - tgba

volumes:
  postgres_data:
